fix: make coverage upload non-fatal, add debug output

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -50,11 +50,13 @@ jobs:
           command : |
             if [[ "$CIRCLE_BRANCH" == "master" ]]; then
               export CC_TEST_REPORTER_ID=99f460f9ae9925e21a7087b218f317c133406bbb278b2980e6441cdebc79ec01
-              curl -fsSL https://github.com/codeclimate/test-reporter/releases/download/v0.11.1/artifacts.tar.gz -o /tmp/cc-reporter.tar.gz
-              tar -xzOf /tmp/cc-reporter.tar.gz ./artifacts/bin/test-reporter-0.11.1-linux-amd64 > ./cc-test-reporter
-              chmod +x ./cc-test-reporter
-              ./cc-test-reporter format-coverage ./coverage.out -t gocov
-              ./cc-test-reporter upload-coverage
+              curl -fsSL https://github.com/codeclimate/test-reporter/releases/download/v0.11.1/artifacts.tar.gz -o /tmp/cc-reporter.tar.gz \
+                && echo "Downloaded: $(file /tmp/cc-reporter.tar.gz)" \
+                && tar -xzOf /tmp/cc-reporter.tar.gz ./artifacts/bin/test-reporter-0.11.1-linux-amd64 > ./cc-test-reporter \
+                && chmod +x ./cc-test-reporter \
+                && ./cc-test-reporter format-coverage ./coverage.out -t gocov \
+                && ./cc-test-reporter upload-coverage \
+                || echo "Code coverage upload failed (non-fatal)"
             fi
 
 
